# Generated by Django 5.0.4 on 2024-05-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_add_actor_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
    ]
