# Generated by Django 5.0.4 on 2024-05-10 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('duration', models.DurationField()),
            ],
        ),
    ]
