# Generated by Django 5.0.4 on 2024-05-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_add_director_model'),
        ('movie', '0001_add_film_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, to='actors.actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actors.director'),
            preserve_default=False,
        ),
    ]
